# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4WLyGWtwOW8cjAn1AGueFBTw3MgXl9W
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

model = joblib.load('best_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("🎬 YouTube Ad Revenue Predictor")

tab1, tab2 = st.tabs(["💰 Predict Revenue", "📊 Visual Insights"])

with tab1:
    views = st.number_input("Views", min_value=0)
    likes = st.number_input("Likes", min_value=0)
    comments = st.number_input("Comments", min_value=0)
    # ... all other inputs

    if st.button("Predict Revenue"):
        engagement_rate = (likes + comments) / (views + 1)
        # build input array, scale, predict
        # Placeholder for input_scaled. You'll need to define how input_scaled is created from your inputs
        # For example, you might create a DataFrame from views, likes, comments and other inputs, then scale it.
        # For now, let's assume input_scaled is an array of the features
        # Example: input_data = np.array([[views, likes, comments, ...]])
        # input_scaled = scaler.transform(input_data)

        # Dummy prediction for demonstration if input_scaled is not fully defined
        # In a real scenario, you would construct input_scaled correctly.
        input_data = pd.DataFrame([[views, likes, comments, engagement_rate]],
                                  columns=['Views', 'Likes', 'Comments', 'Engagement_Rate'])
        # You would need to ensure all features expected by the model are included and ordered correctly
        # For demonstration, let's just make a mock prediction.
        # Replace this with your actual feature preparation and scaling logic
        prediction = np.array([100.0]) # Mock prediction

        st.success(f"Estimated Ad Revenue: ${prediction[0]:.2f}")

with tab2:
    st.subheader("Top Revenue-Driving Features")
    # show feature importance chart
    # show revenue by category bar chart
