# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4WLyGWtwOW8cjAn1AGueFBTw3MgXl9W
"""

"""
YouTube Ad Revenue Predictor
A Streamlit app that uses a trained Lasso regression model to estimate
ad revenue for a YouTube video, and shows model/data insights.
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px
from datetime import date
import os

st.set_page_config(page_title="YouTube Ad Revenue Predictor", page_icon="🎬", layout="wide")

# ---------------------------------------------------------------------------
# Load model artifacts (cached so they're only loaded once per session)
# ---------------------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    model = joblib.load("best_model.pkl")
    scaler = joblib.load("scaler.pkl")
    encoders = joblib.load("encoders.pkl")
    return model, scaler, encoders

try:
    model, scaler, encoders = load_artifacts()
except FileNotFoundError as e:
    st.error(f"Could not load model files: {e}. Make sure best_model.pkl, "
              f"scaler.pkl, and encoders.pkl are in the same folder as app.py.")
    st.stop()

# Feature order must exactly match what the scaler/model were trained on
FEATURE_COLS = [
    "views", "likes", "comments", "watch_time_minutes", "video_length_minutes",
    "subscribers", "engagement_rate", "watch_ratio", "likes_per_view",
    "month", "day_of_week", "category_encoded", "device_encoded", "country_encoded",
]

CATEGORY_OPTIONS = list(encoders["category"].classes_)
DEVICE_OPTIONS = list(encoders["device"].classes_)
COUNTRY_OPTIONS = list(encoders["country"].classes_)

st.title("🎬 YouTube Ad Revenue Predictor")

tab1, tab2 = st.tabs(["💰 Predict Revenue", "📊 Visual Insights"])

# ---------------------------------------------------------------------------
# TAB 1: Predict Revenue
# ---------------------------------------------------------------------------
with tab1:
    st.subheader("Enter Video Performance Details")

    col1, col2, col3 = st.columns(3)
    with col1:
        views = st.number_input("Views", min_value=0, value=10000, step=100,
                                 help="Typical range in training data: ~9,500-10,500")
        likes = st.number_input("Likes", min_value=0, value=1100, step=10)
        comments = st.number_input("Comments", min_value=0, value=275, step=5)
    with col2:
        watch_time_minutes = st.number_input("Total Watch Time (minutes)", min_value=0.0,
                                               value=37500.0, step=100.0)
        video_length_minutes = st.number_input("Video Length (minutes)", min_value=0.1,
                                                 value=16.0, step=0.5)
        subscribers = st.number_input("Channel Subscribers", min_value=0, value=500000, step=1000)
    with col3:
        category = st.selectbox("Category", CATEGORY_OPTIONS)
        device = st.selectbox("Primary Device", DEVICE_OPTIONS)
        country = st.selectbox("Country", COUNTRY_OPTIONS)

    upload_date = st.date_input("Upload / Report Date", value=date.today())

    if st.button("Predict Revenue", type="primary"):
        # --- Feature engineering (must mirror the training notebook exactly) ---
        engagement_rate = (likes + comments) / (views + 1)
        watch_ratio = watch_time_minutes / (video_length_minutes + 0.1)
        likes_per_view = likes / (views + 1)
        month = upload_date.month
        day_of_week = upload_date.weekday()

        try:
            category_encoded = encoders["category"].transform([category])[0]
            device_encoded = encoders["device"].transform([device])[0]
            country_encoded = encoders["country"].transform([country])[0]
        except ValueError as e:
            st.error(f"Unrecognized category value: {e}")
            st.stop()

        input_row = pd.DataFrame([{
            "views": views,
            "likes": likes,
            "comments": comments,
            "watch_time_minutes": watch_time_minutes,
            "video_length_minutes": video_length_minutes,
            "subscribers": subscribers,
            "engagement_rate": engagement_rate,
            "watch_ratio": watch_ratio,
            "likes_per_view": likes_per_view,
            "month": month,
            "day_of_week": day_of_week,
            "category_encoded": category_encoded,
            "device_encoded": device_encoded,
            "country_encoded": country_encoded,
        }])[FEATURE_COLS]  # enforce correct column order

        try:
            input_scaled = scaler.transform(input_row)
            prediction = model.predict(input_scaled)[0]
            prediction = max(prediction, 0)  # revenue can't be negative
        except Exception as e:
            st.error(f"Prediction failed: {e}")
            st.stop()

        st.success(f"Estimated Ad Revenue: **${prediction:,.2f}**")
        with st.expander("See engineered features used for this prediction"):
            st.dataframe(input_row)

# ---------------------------------------------------------------------------
# TAB 2: Visual Insights
# ---------------------------------------------------------------------------
with tab2:
    st.subheader("Top Revenue-Driving Features")

    # Feature importance straight from the trained model's coefficients.
    # Works for any linear model (LinearRegression / Ridge / Lasso).
    if hasattr(model, "coef_"):
        importance_df = pd.DataFrame({
            "feature": FEATURE_COLS,
            "coefficient": model.coef_
        }).sort_values("coefficient")

        fig_importance = px.bar(
            importance_df, x="coefficient", y="feature", orientation="h",
            title="Model Coefficients (impact on predicted revenue)",
            color="coefficient", color_continuous_scale="RdBu"
        )
        st.plotly_chart(fig_importance, use_container_width=True)
        st.caption("Features with a coefficient of 0 were eliminated by Lasso "
                   "regularization — they had little to no impact on revenue.")
    else:
        st.info("The loaded model doesn't expose coefficients (e.g. it's a tree-based "
                "model). Feature importance chart isn't available for this model type.")

    st.divider()
    st.subheader("Average Revenue by Category / Device / Country")

    # Try to compute live stats from the dataset if it's deployed alongside the app.
    # Otherwise fall back to precomputed values so the tab still renders something useful.
    @st.cache_data
    def load_dataset_stats():
        path = "youtube_ad_revenue_dataset.csv"
        if os.path.exists(path):
            df = pd.read_csv(path)
            return (
                df.groupby("category")["ad_revenue_usd"].mean().sort_values(ascending=False),
                df.groupby("device")["ad_revenue_usd"].mean().sort_values(ascending=False),
                df.groupby("country")["ad_revenue_usd"].mean().sort_values(ascending=False),
            )
        return None, None, None

    cat_avg, dev_avg, country_avg = load_dataset_stats()

    # Fallback values computed once from the training dataset
    if cat_avg is None:
        cat_avg = pd.Series({
            "Gaming": 253.51, "Tech": 253.47, "Music": 252.59,
            "Education": 252.48, "Entertainment": 252.45, "Lifestyle": 251.86,
        }).sort_values(ascending=False)
        st.caption("Dataset file not found alongside the app — showing precomputed averages.")

    colA, colB = st.columns(2)
    with colA:
        fig_cat = px.bar(cat_avg, title="Avg Ad Revenue by Category", labels={"value": "Avg Revenue (USD)", "index": "Category"})
        st.plotly_chart(fig_cat, use_container_width=True)
    with colB:
        if dev_avg is not None:
            fig_dev = px.bar(dev_avg, title="Avg Ad Revenue by Device", labels={"value": "Avg Revenue (USD)", "index": "Device"})
            st.plotly_chart(fig_dev, use_container_width=True)
        else:
            st.info("Upload the dataset CSV alongside app.py to see this breakdown.")

    if country_avg is not None:
        fig_country = px.bar(country_avg, title="Avg Ad Revenue by Country", labels={"value": "Avg Revenue (USD)", "index": "Country"})
        st.plotly_chart(fig_country, use_container_width=True)
