# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4WLyGWtwOW8cjAn1AGueFBTw3MgXl9W
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

model = joblib.load('best_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("🎬 YouTube Ad Revenue Predictor")

tab1, tab2 = st.tabs(["💰 Predict Revenue", "📊 Visual Insights"])

with tab1:
    views = st.number_input("Views", min_value=0)
    likes = st.number_input("Likes", min_value=0)
    # ... all other inputs

    if st.button("Predict Revenue"):
        engagement_rate = (likes + comments) / (views + 1)
        # build input array, scale, predict
        prediction = model.predict(input_scaled)
        st.success(f"Estimated Ad Revenue: ${prediction[0]:.2f}")

with tab2:
    st.subheader("Top Revenue-Driving Features")
    # show feature importance chart
    # show revenue by category bar chart